### ISSUE TITLE
Regarding the first question set

### ISSUE THREAD

**Issue by Walter-Feng** [pkozlows/fci#1]
... but thinking of putting both determinants in maximum coincidence and just recording an array of tuples that describe how they differ.

- Yes, that generally is the first step to interpreting the FCI hamiltonian matrix elements. Don't forget the phase factor, as when you try to align the occupation of two determinants, you are sorting the creation operators, and that will cause some possible flips of the sign.

Then, I assume there would be a lot of different doubles, ...

- I am slightly off the topic, is `double` related to a float-point number or a double excitation? If it is a number, generally yes to your question, which I interpret as a "sparse matrix representation of FCI matrix". But matrix is a matrix, it has to be some square matrix in QM point of view. If it's double excitation, generally not, as there can be single excitations. 

How large would the above sum of how many doubles could possibly be?

- That is a question I personally want you to find out. This helps you calculate the complexity of the algorithm.

Is this the right way to calculate that?

- Maybe I did not fully understand your question, but I would think, the term "doubly excited configuration" is not restricted to excitation from ground state, but also among different determinants. That may also address some confusion related to the 'array shape' of the FCI matrix.

**Comment by Walter-Feng** [comment]
A test for referecing the code in condon.py:
https://github.com/pkozlows/fci/blob/52790e98282dd6e565e380786837dd4c0f052c2d/condon.py#L4
[code](https://github.com/pkozlows/fci/blob/52790e98282dd6e565e380786837dd4c0f052c2d/condon.py#L4)

**Comment by pkozlows** [comment]
Then, I assume there would be a lot of different doubles, ...

I am slightly off the topic, is double related to a float-point number or a double excitation? If it is a number, generally yes to your question, which I interpret as a "sparse matrix representation of FCI matrix". But matrix is a matrix, it has to be some square matrix in QM point of view. If it's double excitation, generally not, as there can be single excitations.
How large would the above sum of how many doubles could possibly be?

That is a question I personally want you to find out. This helps you calculate the complexity of the algorithm.
Is this the right way to calculate that?

Maybe I did not fully understand your question, but I would think, the term "doubly excited configuration" is not restricted to excitation from ground state, but also among different determinants. That may also address some confusion related to the 'array shape' of the FCI matrix.

**Comment by pkozlows** [comment]
... but thinking of putting both determinants in maximum coincidence and just recording an array of tuples that describe how they differ.

**Yes, that generally is the first step to interpreting the FCI hamiltonian matrix elements. Don't forget the phase factor, as when you try to align the occupation of two determinants, you are sorting the creation operators, and that will cause some possible flips of the sign.**

https://github.com/pkozlows/fci/blob/52790e98282dd6e565e380786837dd4c0f052c2d/%20main.py#L14
understood about the phase factors. i have been thinking about how to generate the tuples for interpreting the fci matrix elements, but stuck thus far. any hints?

**Comment by pkozlows** [comment]
Then, I assume there would be a lot of different doubles, ...

**I am slightly off the topic, is double related to a float-point number or a double excitation? If it is a number, generally yes to your question, which I interpret as a "sparse matrix representation of FCI matrix". But matrix is a matrix, it has to be some square matrix in QM point of view. If it's double excitation, generally not, as there can be single excitations.**

i mean double excitations.
[11_27 (1).pdf](https://github.com/pkozlows/fci/files/10128640/11_27.1.pdf)
what i mean by my above comment is that for each individual fci matrix element, there would a corresponding array of tuples? (i,j,r,s could equal many things a.k.a a summation would be involved)
https://github.com/pkozlows/fci/blob/52790e98282dd6e565e380786837dd4c0f052c2d/%20main.py#L16

**Comment by pkozlows** [comment]
How large would the above sum of how many doubles could possibly be?

**That is a question I personally want you to find out. This helps you calculate the complexity of the algorithm.**

I need to think about this more, but I have thought about it for a long time (i'm not an expert with combinatorics) and haven't made any progress. Is there some kind of text I could read to get a better idea?

**Comment by Walter-Feng** [comment]
> ... but thinking of putting both determinants in maximum coincidence and just recording an array of tuples that describe how they differ.
> 
> **Yes, that generally is the first step to interpreting the FCI hamiltonian matrix elements. Don't forget the phase factor, as when you try to align the occupation of two determinants, you are sorting the creation operators, and that will cause some possible flips of the sign.**
> 
> https://github.com/pkozlows/fci/blob/52790e98282dd6e565e380786837dd4c0f052c2d/%20main.py#L14
> 
> 
> understood about the phase factors. i have been thinking about how to generate the tuples for interpreting the fci matrix elements, but stuck thus far. any hints?

First you might need to think of a way that well represents the determinants and index them. `Set` in python might be able to help you in representing Fermionic occupation.

**Comment by Walter-Feng** [comment]
> Then, I assume there would be a lot of different doubles, ...
> 
> **I am slightly off the topic, is double related to a float-point number or a double excitation? If it is a number, generally yes to your question, which I interpret as a "sparse matrix representation of FCI matrix". But matrix is a matrix, it has to be some square matrix in QM point of view. If it's double excitation, generally not, as there can be single excitations.**
> 
> i mean double excitations. [11_27 (1).pdf](https://github.com/pkozlows/fci/files/10128640/11_27.1.pdf) what i mean by my above comment is that for each individual fci matrix element, there would a corresponding array of tuples? (i,j,r,s could equal many things a.k.a a summation would be involved)
> 
> https://github.com/pkozlows/fci/blob/52790e98282dd6e565e380786837dd4c0f052c2d/%20main.py#L16

Theoretically no summation is required for a single matrix element in FCI matrix. And for each individual fci matrix element, left is one determinant, right is another determinant.

But if you are saying that tuples represent the excitations (move electrons from their orginally occupied orbitals to unoccupied ones), then sure you are right.

**Comment by Walter-Feng** [comment]
> How large would the above sum of how many doubles could possibly be?
> 
> **That is a question I personally want you to find out. This helps you calculate the complexity of the algorithm.**
> 
> I need to think about this more, but I have thought about it for a long time (i'm not an expert with combinatorics) and haven't made any progress. Is there some kind of text I could read to get a better idea?

Then maybe you can give it a rest for a while - as it will not directly affect writing correct codes. You can definitely investigate it after you have a functioning fci. Not in a hurry. 

Nevertheless, it is also true that an exact number of the occurence of double excitations will be super tedious. Usually an approximation will be useful, for example some double counting of same excitation pattern.

**Comment by pkozlows** [comment]
> > ... but thinking of putting both determinants in maximum coincidence and just recording an array of tuples that describe how they differ.
> > **Yes, that generally is the first step to interpreting the FCI hamiltonian matrix elements. Don't forget the phase factor, as when you try to align the occupation of two determinants, you are sorting the creation operators, and that will cause some possible flips of the sign.**
> > https://github.com/pkozlows/fci/blob/52790e98282dd6e565e380786837dd4c0f052c2d/%20main.py#L14
> > 
> > understood about the phase factors. i have been thinking about how to generate the tuples for interpreting the fci matrix elements, but stuck thus far. any hints?
> 
> First you might need to think of a way that well represents the determinants and index them. `Set` in python might be able to help you in representing Fermionic occupation.

been thinking about this and have an idea. would a list, with occupation indicated by binary of 1 or 0 work? i don't see why a set would help me represent fermionic occupation, as sets are unordered and i need something ordered to keep track of occupations in certain orbitals.

**Comment by Walter-Feng** [comment]
It can work- just some possible ways of representing the excitations.

well,  I prefer set because a set is defined to have unique elements, such uniqueness exactly corresponds to the occupation pattern of fermions. This allows me utilize some set operations like intersections and XORs that helped me identify the excitations. 

But it’s completely ok if you have your preferred way. Although it will be interesting to discuss which one performs better (as I recall sets can have some hash-ish thing that reduce the complexity), it’s not an important topic in either FCI or this FCI tutorial.

**Comment by pkozlows** [comment]
> It can work- just some possible ways of representing the excitations.
> 
> well,  I prefer set because a set is defined to have unique elements, such uniqueness exactly corresponds to the occupation pattern of fermions. This allows me utilize some set operations like intersections and XORs that helped me identify the excitations. 
> 
> But it’s completely ok if you have your preferred way. Although it will be interesting to discuss which one performs better (as I recall sets can have some hash-ish thing that reduce the complexity), it’s not an important topic in either FCI or this FCI tutorial.

I see. I think sets could work well for the uniqueness, but I am confused how it is possible to use them to represent determinants, as they are unordered and it seems like having an ordered data structure to represent determinants would be useful. Could you send an example of one such determinant with a set, so I can get more of an idea of how it would work?

**Comment by Walter-Feng** [comment]
It’s just that the element (the number) represents the index of the spin orbital, and whether or not having this number represents the occupation of an electron in that spin orbital.

I have my FCI repository in my GitHub, which uses sets in python. Personally I don’t recommend you reading it right now, as I hope this can be an independent project, at least on the coding side. Nevertheless, it’s also up to you to decide which way you benefit the most from.

**Comment by pkozlows** [comment]
> It’s just that the element (the number) represents the index of the spin orbital, and whether or not having this number represents the occupation of an electron in that spin orbital.
> 
> I have my FCI repository in my GitHub, which uses sets in python. Personally I don’t recommend you reading it right now, as I hope this can be an independent project, at least on the coding side. Nevertheless, it’s also up to you to decide which way you benefit the most from.

That set implementation makes sense. The one part that is not clear to me is how do you keep track of the phase factor when using sets? I think I want to try implementing the determinants as set, as opposed to lists, first because I too think that set operations, like intersection, could be useful.

I definitely want to try implementing without looking at your solution first.

I know I am asking a lot of questions now and not writing a lot of code yet, but because the fine motor task of implementation will take time for me, I want to somewhat think through my implementation before doing it.

**Comment by Walter-Feng** [comment]
I might want to keep it as a secret for you regarding the phase factor - as this reinforces your understanding of second quantization. Just as a hint, you should identify *WHEN* the phase factor is involved, i.e. changing the order of creation / annihilation operators is required during FCI hamiltonian construction.
