### ISSUE TITLE
Error in HF energy

### ISSUE THREAD

**Issue by pkozlows** [pkozlows/fci#11]
https://github.com/pkozlows/fci/blob/fddc0e2f127193eca0008c12dbac535acc959fb3/condon.py#L111### 

So, it seems that I'm getting something wrong with my einstein summation notation in this if state. This Is why I am printing incorrect val of HF energy later in the file. I thought i modeled my einstein summation notation correctly based off of the equations in questions/2-9.pdf, but evidently not. If this einstein summation notation is incorrect, I probably ought to learn a that bit more about the einstein summation notation, because it seems to be use fairly freq in manipulations with tensors that I will be doing a lot of in the future?

**Comment by Walter-Feng** [comment]
Ah well I don't think you made a mistake in einstein summation. Rather it's the Slater-Condon rule that might have got something wrong.

I also recall the mistake here. Note that we are focusing on *spin orbitals*, i.e. the integral of spin will also be involved in this situation.

**Comment by pkozlows** [comment]
I guess I always thought of the condont rules in terms of spatial ial orbs. So, for one body operators, I imagine that there would not be any relevant integrals over spin to worry about? I would just have to think about how to incorporate ints over spin into two body operators?

**Comment by Walter-Feng** [comment]
You might still need to think about one body operators with spin, but in a more trivial way than two-body operators.

**Comment by pkozlows** [comment]
So, if I am understanding this covertly,

https://github.com/pkozlows/fci/blob/fddc0e2f127193eca0008c12dbac535acc959fb3/condon.py#L112

 is taking the trace of the entererity of h1e.npy, but I should be only taking the trace of the first half of this array * 2, since for the 1e Hf energy, the alfa and beta spin orbitals both take on the spatial orbital valgus of 0 to 2, So I shouldn't be accessing indices 3 thru 5.. in this way, thinking about the one body ops in terms of spin is more trivial than for the two body ops, but I still need to make a correction for the one body operators. Hope this makes sense?

The eqns that I'm thinking about are in questions/2-10_v2.pdf  in case you need a clans.

ci my chatgpt misrecog script is failing me for the past few days :-(, in case u were wondering about the typos, but  you should be able to still understand.

**Comment by Walter-Feng** [comment]
Yes, that will be correct.

Note that in actual researches there can be hardly anyone who can guarantee you if something is correct or not. You have to make unit tests yourself, find out what is the most sensible in your logic, and stagger through the bugs and problems. At least for now, you have the correct numbers to compare with (HF, FCI), so that you have clear idea of you are having some bugs. 

You might try tackling the two-electron integrals without my hints. If you still fail to match the number, take it easy, have good rest, but reflect constantly.

still, I hope that the struggle with 1e/2e integrals in HF helps you get rid of the naïve classification of ground state, singles and doubles for determinant basis. Either from second quantization or linear algebra, you can find clues that such a classification will not work as what you would expect. 

so how should I debug with my gpu code? Sigh… I wish there could be someone helping me with the debugging, but you know, C++ is hard, GPU C++ is harder, GPU C++ for 2e integrals is even harder. Most of the time we have to fight alone.

**Comment by pkozlows** [comment]
Thank you for the help.

For both your sanity and mine, I think I need to think out my questions a little more before asking you them.

What it be possible to get the HF 1e and 2e energy so I can check with them once I figure out my implementation?

Also, I need to think a little more about how to do unit test on my functions because this will be very helpful.

**Comment by Walter-Feng** [comment]
No it’s not like I am growing tired of helping - I’m always glad to help. But just that helping out with every detail may not be really helping you learning quantum chemistry or programming. 

One electron integral gives -12.42356787. I don’t guarantee it’s correct ;)

**Comment by pkozlows** [comment]
I'm having some issues figuring out how to implement the orthonormality of spin orbs into the two-electron matrix elements. I know that the orthonormality of spin orbs doesn't matter for the first einstein sum, but it should lead to some cancellations for the second one. How would I take this into account? I have attached the images of the equations I'm thinking about with this problem.

![PXL_20230217_042732852.jpg](https://user-images.githubusercontent.com/59596755/219549655-d756d052-b959-4d30-80bd-f5e490506c15.jpg)

![PXL_20230217_042813510.jpg](https://user-images.githubusercontent.com/59596755/219549670-cc832885-0ade-4c61-84a1-1c22783e9f47.jpg)



https://github.com/pkozlows/fci/blob/f69fbc67989517a338ea3e6104d59325d49e5ea6/condon.py#L115

**Comment by pkozlows** [comment]
Maybe I need to get a better understanding of the Einstein. Some notation?

**Comment by pkozlows** [comment]
Also while I have you here is GitHub copilot something people in quantum chemistry Or does programming in the field require two much advanced knowledge for artificial intelligence to butt in? I'm wondering whether it's worth trying it out.

**Comment by Walter-Feng** [comment]
I don’t think that is called an orthogonality - Orthogonality is only involved when overlap is taken into account. It should be part of the Slater-Condon rule.

Copilot - I recall Junjie has used it and was giving good comment, but it will be a cheat to you, as it does not improve your coding skill. You don’t think writing a comment “A function that implements full CI algorithm” and generating a full CI program can be defined as you learned Full CI, right?

**Comment by pkozlows** [comment]
The Condon rule that I'm using for this two electron matrix element is case 1 in the image above. I tried to implement this in the link line above. I know my implementation does not take into account that I am dealing with spin orbitals though, but I'm not sure how I would implement this. You said above that spin should be part of the Condon rule, but I don't see any mentions of spin in it.

**Comment by Walter-Feng** [comment]
Indeed slater condon rules will not be mentioning spins- but if you read the slater condon rules carefully, you should not see anything that the slater condon rule will directly represent the elements of the FCI matrix.

The implementation can be dirty - important thing is you develop the ability to translate math in a computer programming language. Only after this, can you develop the taste of what makes a piece of code elegant.

I hope you can still buy a few days to iterate over this. This will make you stronger.

Don’t hesitate to implement your ideas. In most cases you will quickly understand what is deficient once you start to implement, but only after you start to implement. Adding members to an object can quickly overcome such deficiency.

**Comment by pkozlows** [comment]
https://github.com/pkozlows/fci/blob/227141bee774e4f3f938bdd84b1ea26f87da5150/condon.py#L113

I have pushed my questions to a fil in the questions directory

**Comment by pkozlows** [comment]
So the part that I'm confused about is how I would change my implementation of the second einsum in the linked line, which presume corresponds to exchange ints, to take into account spin.

**Comment by pkozlows** [comment]
Actually, now I realize that some of my verbiage like the exchange or coloumb ints. Might be in accurate. But the overall meaning of my question, other than the verbiage should be correct.

**Comment by Walter-Feng** [comment]
You can either add spin to your electron object and check if the spin combination satisfies some certain criteria, or generate the alpha and the beta electrons seperately, and perform summation case by case.

**Comment by pkozlows** [comment]
So, using the Einstein sum for accessing the spatial orbitals of  [mm|nn] Would be okay, but I would need a different possibly case by case basis for [mn|nm]?

**Comment by Walter-Feng** [comment]
I would guess so, but nothing too different right?

**Comment by pkozlows** [comment]
So, I guess what I was driving at is that in the linked line, the first Einstein sum would be okay as it is, but I would need to change the second einsum to take into account spin, and to  Do that I would want to get rid of the second einstein some and deal with electron spin on a case by case basis instead.

https://github.com/pkozlows/fci/blob/227141bee774e4f3f938bdd84b1ea26f87da5150/condon.py#L113

Also, I know that generally implementing mathematics into code is a good way to figure out the issues I have, but I have found that since I need to do my physical rehabiliation any ways, having full configuration interaction to think about in the meantime is pretty nice, and then when I sit down to my laptop the implementation is easier because ready have thought of an idea for it.

**Comment by Walter-Feng** [comment]
Well, both coulomb and exchange requires some treatment for the spins, i.e. each of them should be a summation of a few terms instead of one single einsum.

**Comment by pkozlows** [comment]
https://github.com/pkozlows/fci/blob/1c7726b28ac9400965c6f95fc6d2bf907c9caf28/questions/2-21.pdf

**Comment by Walter-Feng** [comment]
Spin is nothing about spacial coordinates, so there is no such thing as the integral of spin over the space.

Full CI is not necessarily about integrals. Mind that the energy expression has nothing to do with integrals, but the creation and annihilation operators. Only when you reduce the super long operator string into a compact form of one pair or two pair, will you be able to convert it to an integral. 

Spin is then easy to understand, as the commutation rule between different spins are just different.

**Comment by pkozlows** [comment]
I am still confused about how I will deal with the case of two determinants who have no differences. When I am able to deal with this case, I should also be able to deal with the cases of one pair or two pairs of diffs, as I will understand how to deal with differences in spin. In general, I think that I am getting a better understanding of how to incorporate spin into full configuration interaction. So, for [ij|kl], which I think corresponds to the probability of transferring one electron from the i spin orbital to k, and j to l, there would be a cancellation if i and k had different spins. So, when I'm dealing with [mm|nn], if m and n have different spins, a cancellation would occur. And also for [mn|nm],  the same would occur if I am exchanging m for n, when they have diff spins.

Also, I think the Einstein summation in my code is slowing me a little bit bc I don't understand it, so I think that the best thing would be to implement my ideas first with for loops and then once that works, to go back and change them to Einstein summations, which is more efficient. what do you think?

**Comment by Walter-Feng** [comment]
Sure it can be ;) it's more important to get things right first
