### ISSUE TITLE
error in 2 electron mel of HF Energy

### ISSUE THREAD

**Issue by pkozlows** [pkozlows/fci#13]
If you have some time, could you take a look at the linked code? It involves for loops, which I understand, but it's still giving me an incorrect output. Can you offer any hints as to what I'm doing wrong?lines 114-line 126 is whqt ive workked onn.

https://github.com/pkozlows/fci/blob/fcc4f3e79515653ed0bdde38f9c79d75a6e173c7/condon.py#L114

**Comment by pkozlows** [comment]
From what I understand, I'm probably doing some things right, but nevertheless I'm putting out incorrect energy. What do I need to think about some more?

**Comment by Walter-Feng** [comment]
Why do you need to divide everything by 2?

**Comment by pkozlows** [comment]
D Reason was to convert the spin indices that I am iterating through into spatial indices.

**Comment by pkozlows** [comment]
Because from what I understand, it is from the spatial indices that I can access the integrals.

**Comment by Walter-Feng** [comment]
Then why do you judge by the mod of m and n by 2?

**Comment by pkozlows** [comment]
To check whether a given spin orb has spin up or down. N then, later, in my code, I do a floor division of the spin. Orb index by two in order to convert to spatial orb index For accessing the integrals.

**Comment by Walter-Feng** [comment]
Good, are you doing coulomb? Or exchange?

**Comment by pkozlows** [comment]
I'm doing the same for both.

**Comment by pkozlows** [comment]
Because I understand that in both the column and exchange cases, I need to convert the spin, orbs into spatial orbs,

**Comment by Walter-Feng** [comment]
If the determinant you are treating is actually an rhf case, how can it be converted to 2J - K expression?

**Comment by pkozlows** [comment]
![PXL_20230217_042732852.jpg](https://user-images.githubusercontent.com/59596755/221041781-97a37be2-8f9a-4867-81a0-820074572cfc.jpg)

I am just trying to implement case one in the attached image. Maybe I need two developed, a better understanding for terms, column, and exchange though?

**Comment by pkozlows** [comment]
I imagine that case one should still work for the case?

**Comment by Walter-Feng** [comment]
I wrote the code according to the book, but the numerics are not correct, what should I do?

Therefore the questions that help ourselves have a clear mind about what we are doing, and reduce to something we have better understanding about. Maybe the book is telling the truth, but there are something that are not covered.

**Comment by Walter-Feng** [comment]
For example, the spin.

**Comment by pkozlows** [comment]
Do you have a recommendation for how to devote up a better understanding of the spin? lol

**Comment by pkozlows** [comment]
I see that the textbook you sent me earlier might have a good treatment for this, so maybe that's a good place to start?

**Comment by Walter-Feng** [comment]
Write operator string. Consider He where only 1s orbital is involved. Only use the commutation rule to get all the terms

**Comment by pkozlows** [comment]
From a first glance, I think this text has exactly what I need.

**Comment by Walter-Feng** [comment]
It can be, but I always believe a minimal example can quickly identify the problem.

**Comment by pkozlows** [comment]
operater_string = [(0,0),(1,0),(0,1),(1,1)]

This is for the minimal helium case <01|01>.

 What do you mean then by this? My thought is that it would simply lead to a cancellation of all the second quantization strings and spit out and associated face factor.

>Only use the commutation rule to get all the terms

**Comment by Walter-Feng** [comment]
This example only involves spin up and down, so if only involving two electron integrals, it will be “abPQrsBA” sandwiched by two vacuum states. a for alpha, b for beta, pqrs for generic index that are summed, capitalization for creation operators.

**Comment by pkozlows** [comment]
abPQrsBA

I see how such a notation could be very useful, but I don't quite understand it. What does abPQ do on a vacuum state?

Also, I hope I'm not causing too much of an inconvenience with my rapid questions today. If it is too distracting, actually let me know. And I will think more over things before asking questions.

**Comment by Walter-Feng** [comment]
ab from bra state, PQ a portion of the two electron integral.

**Comment by pkozlows** [comment]
I'm still confused about how to incorporate spin requirements into my code. I have an operator list that looks like this: [(5, 0), (4, 0), (3, 0), (2, 0), (1, 0), (0, 0), (0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1)] for the RHF determinant pair. How would I think about using an 2e- operator on this string? Is the abPQrsBA notation referenced earlier useful mainly from a mathematics perspect or should i try to implement this into my code, as opposed to something like the above op list?

I think I'm understanding that doing this in second quantization will make life a lot easier, but I'm not sure how to do so. Can you give any starting points without giving the whole solution away? If I'm understanding this correctly, then the equation given in the book is correct from a spatial perspective, but it does not take into account spin.

**Comment by Walter-Feng** [comment]
That’s why you would like to solve the minimal example first. Just try to reduce the He2 to a set of two-electron integrals.

**Comment by Walter-Feng** [comment]
You should be solving it mathematically, identifying which part should be coulomb, which part should be exchange. Then you compare with how you wrote the code, and I guess you can find out what made it wrong.
