### ISSUE TITLE
what to do next after getting a correct hf e?

### ISSUE THREAD

**Issue by pkozlows** [pkozlows/fci#14]
https://github.com/pkozlows/fci/blob/b0cd57ea8697e26f1845ca1b4230e171002ee14f/condon.py#L106

getting a correct hf E with lines 106-122. Do you recommend that my next goal should be to make the existing code more efficient by incorporating ein summations, which I don't yet have an idea on how to do, or should I move on to address the cases where there are differences between the two dets? If it is the latter case that you recommend, could you give me some examples of a certain det pair with the energy that u get so that I could compare for debugging? i would want Es for cases w 1 and 2 diffs between dets.

**Comment by Walter-Feng** [comment]
I would recommend going for a generic FCI matrix and perform diagonalization. 

If you implement correctly, you should be seeing tons of zeros, e.g. the element for ground state and first excited state (if I recall correctly). Then you can directly compare if you have generated the correct eigenvalue.
