### ISSUE TITLE
Should I figure out the einstein some or use pauling?

### ISSUE THREAD

**Issue by pkozlows** [pkozlows/fci#15]
My implementation using for loops is so per slow, as expected, so I am wondering if incorporating einsum, Which I don't completely understand yet, would speed up the full configuration intervention mat genervation enough or what I want to use a supercomputer like pauling any ways? I have not Learned to use this supercomputer prefer, so I would need to learn how to summit jobs to it, which I imagine would be fairly simple. I got a login to pauling from Mark, so I have that covered, but I would need to learn how to submit jobs to it.

**Comment by Walter-Feng** [comment]
Theoretically using a super computer will not be helping, as you are using single thread, and CPUs on super computers won’t be having a better single-thread performance than PCs.

**Comment by pkozlows** [comment]
For reference. How long does your fill configuration interaction, matrix generation take to run? I'm wondering how long I need to wait for this to be normal or if I should right away. Try to make my implementation more efficient.

**Comment by Walter-Feng** [comment]
There were several optimizations beyond the einsum, so not too much to worry about - it was 1.36s from start of the program to getting the eigenvalue. Matrix generating process should be taking less time than that.

**Comment by Walter-Feng** [comment]
And maybe I was using a more powerful CPU, so time may vary.
