### ISSUE TITLE
Matrix generation taking too long

### ISSUE THREAD

**Issue by pkozlows** [pkozlows/fci#18]
Let's assume that I will eventually get a correct implementation of the Condo roles, because I feel like I'm getting there. I tried to generate the full configuration interaction matrix, but it took a few minutes and I know that that's not right. Do you have any tips off the top of your head for speeding this up? I'm thinking that it might have something to do with the fact that I'm initializing the matrix with zeros in the beginning and I might not need to do that?

https://github.com/pkozlows/fci/blob/0a07755bae6850e045679e39e7524ae7880dc8b1/%20main.py#L23

**Comment by pkozlows** [comment]
Chad GPT suggested this. Are these tools you would recommend for me?

>Optimize the code: You can use profiling tools like cProfile or PyCharm's built-in profiler to identify the parts of your code that are taking the most time to execute. Once you have identified these bottlenecks, you can try to optimize the code by using more efficient data structures, avoiding unnecessary computations, and reducing the number of function calls.

**Comment by Walter-Feng** [comment]
np zeroing is required but should not taking much time, around milisecond level.

Yes, it will be helpful if you use profiling tools to check it, cProfile is a good start. Snakeviz is a good visualizer for cProfile.

**Comment by pkozlows** [comment]
So, spending a lot of time in these two functions, but I don't know how to make it more efficient. The input has to be a set for the sake of efficiency, but I have to eventually converted to an ordered list of operators, because the ordering is relevant if I want to compute the phase factor. Do you have any tips off the top of your head?

544698   12.968    0.000   20.044    0.000 condon.py:43(bra)
   544698   12.351    0.000   19.206    0.000 condon.py:31(ket)

https://github.com/pkozlows/fci/blob/ed863489a83aedef34ae354350a020e8d2969934/condon.py#L31

**Comment by pkozlows** [comment]
I know that you once said it took you just under 2 seconds from the start of your program to get the energy. I know that the current state of my program, which is taking just under 2 minutes to run, is not good, but I'm wondering what kind of time I should strive for from the start of my program to get the energy.

**Comment by pkozlows** [comment]
I'm not noticing anything inherently wrong with both of these functions so maybe I'm just calling them too many times?

**Comment by Walter-Feng** [comment]
Yes, per function call the time is not too crazy, but it is not something that takes half a million’s function call.

**Comment by pkozlows** [comment]
Now, program is taking 11 seconds, instead of 110, Which is a step in right direction. Since my basis doesn't contain numbers but instead a ordered list of sets that contains relevant information, I don't see how I can use numpy to get rid of the for loops here. If the program should be taking faster, am I missing something here?
https://github.com/pkozlows/fci/blob/011f5d2a712936ae7c336a478cde291208e31e8d/%20main.py#L32

**Comment by Walter-Feng** [comment]
Well, if it's 11 seconds, which is not too bad, you can just rest it and focus on getting the numbers right. I recall mine uses a sparse structure so probably faster than 11 seconds. Plus there might be difference of processors.

**Comment by Walter-Feng** [comment]
Further it uses Davidson's diagonalization algorithm which makes faster, but I guess you have not implemented it. So that might affect your performance as well.
