### ISSUE TITLE
> Then, I assume there would be a lot of different doubles, ...

### ISSUE THREAD

**Issue by pkozlows** [pkozlows/fci#2]
> Then, I assume there would be a lot of different doubles, ...
> 
> **I am slightly off the topic, is double related to a float-point number or a double excitation? If it is a number, generally yes to your question, which I interpret as a "sparse matrix representation of FCI matrix". But matrix is a matrix, it has to be some square matrix in QM point of view. If it's double excitation, generally not, as there can be single excitations.**
> 
> i mean double excitations. [11_27 (1).pdf](https://github.com/pkozlows/fci/files/10128640/11_27.1.pdf) what i mean by my above comment is that for each individual fci matrix element, there would a corresponding array of tuples? (i,j,r,s could equal many things a.k.a a summation would be involved)
> 
> https://github.com/pkozlows/fci/blob/52790e98282dd6e565e380786837dd4c0f052c2d/%20main.py#L16

Theoretically no summation is required for a single matrix element in FCI matrix. And for each individual fci matrix element, left is one determinant, right is another determinant.

But if you are saying that tuples represent the excitations (move electrons from their orginally occupied orbitals to unoccupied ones), then sure you are right.

_Originally posted by @Walter-Feng in https://github.com/pkozlows/fci/issues/1#issuecomment-1333171624_

I don't think I was previously clear with this question. What I mean is that wouldn't a lot of individual FCI matrix elements be a large sum (array) of the different excitations that are possible? Looking at 11_27 (1).pdf, for the rightmost determinant, i and j could equal to 1,...N, while r and s could equal N...2m, where N is the number of electrons and m is the number of orbitals (2m because 2 electrons to an orbital), so there are multiple excitation possibilities for all but the ground state determinant, corresponding to many possible determinants that can be labeled as singles, doubles, triples, etc. Thus, any individual FCI matrix element, that does not just involve two ground state determinants, has many possibilities for what one (or both) of its non-ground state determinants could be and each FCI matrix element would, in fact, be represented by an array that takes all the different combinations into account. Hope this makes sense?

Actually let me know if you don't completely know what I'm asking about; I am happy to create a Latex file with a visualization for what I am asking. It's just that writing up a new Latex file takes extra time for me given my fine motor impairment (when I learn how to dictate for Latex, it will speed things up considerably). But you not understanding what I'm asking because of a lack of proper visualization is waste of time, for you and for me; because of this, I am happy to spend some extra time creating a visualization with Latex, if it is helpful.

**Comment by Walter-Feng** [comment]
I still feel that your clarification is against my understanding of Full CI. 

I believe you are not talking about CSF functions but in a determinant basis, then a specific FCI matrix element only involves two corresponding determinants, whose pair has only one single pattern of excitation. They do not have to be relevant with ground state determinant. So there will only be an array of *electrons*, or more precisely *spin orbitals*, that is involved in FCI matrix element.

It might be that my word "excitation" is slightly confusing - but I still believe that the concept of excitation, originally being "the different occupation of orbitals compared to ground state", can be applied to any determinant pair, not necessarily related to the conventional terms "single", "double", etc.

It is also possible that you have different understanding of FCI than mine, or that I am bad at understanding scientific perspectives from others, so no worries if we fail to convince each other. You can just follow your own thoughts and try implementing to see if you understand correctly.

**Comment by pkozlows** [comment]
> I still feel that your clarification is against my understanding of Full CI.
> 
> I believe you are not talking about CSF functions but in a determinant basis, then a specific FCI matrix element only involves two corresponding determinants, whose pair has only one single pattern of excitation. They do not have to be relevant with ground state determinant. So there will only be an array of _electrons_, or more precisely _spin orbitals_, that is involved in FCI matrix element.
> 
> It might be that my word "excitation" is slightly confusing - but I still believe that the concept of excitation, originally being "the different occupation of orbitals compared to ground state", can be applied to any determinant pair, not necessarily related to the conventional terms "single", "double", etc.
> 
> It is also possible that you have different understanding of FCI than mine, or that I am bad at understanding scientific perspectives from others, so no worries if we fail to convince each other. You can just follow your own thoughts and try implementing to see if you understand correctly.

I think I understand more now. It is not a determinant basis for the fci matrix, but a csf basis. I don't completely understand what a csf is, which i guess means that i need to read up on the topic. is the csf similar to a symmetry-adapted linear combination? i know SALCs combine determinants, such that they are eigenfunctions of the spin operators, i.e. SALCs are pure singlets, doublets, triplets, etc. are csfs a related concept? i assume i have to come up with an algorithm that produces csfs for a given excitation magnitude out of all possible determinants with that excitation magnitude?

**Comment by Walter-Feng** [comment]
I believe it will be a lot easier to implement determinant basis instead of CSF basis. 

[Wiki](https://en.wikipedia.org/wiki/Configuration_state_function#:~:text=In%20quantum%20chemistry%2C%20a%20configuration,be%20confused%20with%20a%20configuration) got a solid explanation so you can check it out.

**Comment by pkozlows** [comment]
[12-7.pdf](https://github.com/pkozlows/fci/files/10181217/12-7.pdf)

**Comment by Walter-Feng** [comment]
Your notation confirms that you are indeed thinking about FCI in a determinant basis. Then no, all such possible double excitations (from ground state) should *NOT* be a linear combination, but different dimension for a CI vector. You can review Fock space in second quantization and figure out what is really linearly combined in this space.

I believe you should jump out of the HF ground state determinant and think about the general picture - just generate all possible determinants, compare their excitations, and generate FCI matrix. Some alternative way to say it, \Psi_0 can generally not be a Hartree-Fock ground state, but any arbitrary determinant.

"determinant basis" is super important understanding the linear-algebraic structure of FCI. For example, the dimension of Full CI matrix is not directly related to the "shapes" of O1 and O2.

**Comment by pkozlows** [comment]
> Your notation confirms that you are indeed thinking about FCI in a determinant basis. Then no, all such possible double excitations (from ground state) should _NOT_ be a linear combination, but different dimension for a CI vector. You can review Fock space in second quantization and figure out what is really linearly combined in this space.
> 
> I believe you should jump out of the HF ground state determinant and think about the general picture - just generate all possible determinants, compare their excitations, and generate FCI matrix. Some alternative way to say it, \Psi_0 can generally not be a Hartree-Fock ground state, but any arbitrary determinant.
> 
> "determinant basis" is super important understanding the linear-algebraic structure of FCI. For example, the dimension of Full CI matrix is not directly related to the "shapes" of O1 and O2.

12-14.pdf

**Comment by pkozlows** [comment]
the 12-14.pdf file will be in pkozlows/fci/questions

**Comment by Walter-Feng** [comment]
1. Well, I guess you don't really need to do an explicit calculation of that. You can first get all the determinants and count the number of them, then start generating a matrix.
2. Let's denote < i -> r | O1 + O2 | i, j -> r, s > for the 'matrix element' you provide in this section. No, they won't fit. I use quote here because < i -> r | O1 + O2 | i, j -> r, s > is not "the form you want" in FCI matrix. < 6 -> 12 | O1 + O2 | 5,6 -> 11, 12 > and <5 -> 11 | .... | ... > will be two independent elements. 
3. I don't think it's simple, but yes, generally it starts from Slater-Condon rules.
4. Cool, I can read your dictation. Looks good ;)

**Comment by pkozlows** [comment]
Hope you had a happy holidays. I'm experimenting a lot with using dictation to program now, but I need a code to work with so That I know  what I need from the dictation, if that makes sense, so I want to be slowly working on this project  at the same time. I haven't done any serious code dev yet, and I think now is the time for me to start. T

 In reguards to the project I think, I think I worry about the matrix elements and the slater condi  rules when I get there, I just need to figure out the algorithm for generating all possible determinants before worrying aabt simplifying. I've been stuck on this for a few weeks though and I was wondering if you have any hints that don't involve showing me your code lol.  I don't have a code written yet for implementing the generation algorithm, which I know isn't helpful, but I guess what might helpful is if you could recommend some  Example code for me to emulate. Or alternatively, if you think this would be more helpful, I could write some very rudimentary code for trying to implement the algorithm. Maybe having some code to work with would be helpful in this situation. that me know what you think.

**Comment by pkozlows** [comment]
Actually, I have an idea for an algorithm. It will be defended be helpful for me to start by implement some code, so that we have something to talk About.

**Comment by Walter-Feng** [comment]
Sorry for the late reply - I am glad you got an idea for the algorithm! You are doing good - it just takes that much time and effort to get through. 

I understand it might be relatively tough directly starting with the determinant generation. I have some super tiny projects that either you can try or see how I do, so that you can follow how to think like a programmer. The tiny projects can be, for example, a random walk model, in 1 dimension, in 2 dimensions and so on. It can also be, generating the pairs of two indices (which might be helpful in our context). 

Let me know if I could be of any help. More than happy to assist you - I am not directly giving the answer just because this way you will learn more ;) not meant to manually add difficulty

**Comment by pkozlows** [comment]
A pink tiny projects, such as random walk models, might be helpful for me. I am curious to see what they look like. I am currently trying to generate all possible determinants, but it is a little tricky if I don't completely understand how random works work.

What does generating the two pairs of indices mean? I'm not completely following. This might be helpful for me to.

Maybe I should show you my code for this, but I'm thinking that the determinants themselves should be represented but the data type sets, but the collection of all possible determines would be compiled in a list?

**Comment by Walter-Feng** [comment]
generating the two pairs of indices - sorry I was not making it clear. For example, you have N orbitals, and you would like to generate all possible pairs of N orbitals by their indices, so it can be (0, 0), (0, 1), ... well it's literally for loops, but then we can make it like, finding all the combinations of orbitals in two lists.

random walk is super simple, for example in one dimension, per each step, you have 50% for going left by one unit, and you have another 50% for going right by one unit. go 100 steps check the final position, and this is 1 trajectory. Gather 100 trajectories and see the distribution of the final positions.

I did not quite understand the third line - I guess you were saying "the determinants themselves should be represented *by* some data structure, but the collection of all possible *determinants* would be compiled in a list" ? Ah yes that is generally true.

**Comment by pkozlows** [comment]
In regards to generating the two pairs of indices, I can vaguely see that don this would be useful for what I want to do, but I don't yet specifically see how it would help.  if you could enlighten me a little bit lol

 I understand the principle behind the Random walk, but I don't see how  a distribution of final positions would help with the determined generation that I'm trying to do. If I'm nod mistaken, isn't the det config with lowest probability just as important for my determanent generation as the config which appears most often?

 This is very hopeful, but I think I actually need to write up some code us to look at before we can dive deeper into this question.I well push new code to my repository in the next few days.

p.s.  Dictation is really a breath of fresh air for me, both in terms of dictating messages and for programming, because I really feel that things which use to be cognitively challenging from me are still that way, which is normal, but it's nice for me to not feel limited by my motor impairment, if that make sense.

**Comment by Walter-Feng** [comment]
Eh pairs of indices - it essentially is how I generate the determinants (though it will then be tuples instead of pairs).

Random walk is just a tiny project that helps you get familiar with coding - easy to write, easy to check results. Not specifically relevant to full ci code.
