### ISSUE TITLE
Don't understand why h1e.npy isn't symmetric?

### ISSUE THREAD

**Issue by pkozlows** [pkozlows/fci#21]
I printed out h1e and h1e.T and struggling to understand why these wouldn't be the same, while every _other_ element is equal to its transposition, if this make sense.  I imagine that the case is the same for h2e. I'm feeling that my lack of understanding here might be the reason why I am not getting <GS|H|single_excitation> = 0, as I should.

**Comment by Walter-Feng** [comment]
I don't think that's the case.

```
>>> import numpy as np
>>> np.load("h1e.npy")
array([[-2.28175193e+00,  3.33066907e-16,  1.45866827e-01,
        -7.21644966e-16, -6.41863903e-02,  0.00000000e+00],
       [ 1.66533454e-16, -2.04094527e+00, -3.88578059e-16,
         2.11059202e-01,  1.33226763e-15, -4.17230433e-02],
       [ 1.45866827e-01, -1.66533454e-16, -1.88908673e+00,
         2.22044605e-16, -1.73905985e-01,  7.21644966e-16],
       [-5.96744876e-16,  2.11059202e-01,  2.77555756e-16,
        -1.67570187e+00, -2.77555756e-16, -1.53542384e-01],
       [-6.41863903e-02,  1.20736754e-15, -1.73905985e-01,
        -1.38777878e-16, -1.38367991e+00,  2.91433544e-16],
       [ 3.92047506e-16, -4.17230433e-02,  3.67761377e-16,
        -1.53542384e-01,  4.85722573e-17, -1.20982661e+00]])
>>> a = np.load("h1e.npy")
>>> np.max(np.abs(a - a.T))
4.926614671774132e-16
```

**Comment by pkozlows** [comment]
Be floating point error was just messing me up.

**Comment by pkozlows** [comment]
I am getting that <GS|H|single_excitations> are close to 0. However, I am not getting a correct fci energy yet. i'm just wondering if for brillouins thm <GS|H|single_excitations> must exactly = 0, or if there is a tolerance factor i.e. What i did in my asserts in the linked code. MOre generally, I just want to check if any floating point ever is acceptable in my code, or if quantities must match exactly with what you got or those in the instructions.

https://github.com/pkozlows/fci/blob/0473d0e45208fcb44d70c778296517690eea33c2/slater.py#L109

**Comment by Walter-Feng** [comment]
Although it depends on the system size as well as the types of calculation (that affects the number of operations to get the value), usually 10^-8 ~ 10^-12 can be regarded as some tolerable error for two numbers to be equal. In this case, 10^-12 can be a targeting error.

things change when the number itself is 0. Consider two numbers, 4 * 10^-16 and 8 * 10^-16. Absolute error ~ 0, rel error = 1.
