### ISSUE TITLE
what tolerances in my unite tests are acceptable?

### ISSUE THREAD

**Issue by pkozlows** [pkozlows/fci#24]
if I am getting
[1.01099822e-08]
[1.23861594e-08] 
for some unit test for < hf_gs |H| single_excitation > and
[-1.97975317e-16]
[-2.76037873e-16]
[3.42824727e-16]
for others, is this problematic?
I know that you previously said that in electronic structure, a tolerance of 1e-3 is needed, but did you mean this for individual energies, or just for important eigenvalues, like the fci energy?
I noticed that in your code most of your unit tests have a tol of 1e-13, so that's why I'm asking.
it is looking like this debugging session is going to be a while, so I just want to make sure that my tolerances for unit tests are good (as the hf energy and above brillouin's thm are my main things to go off) :-)

**Comment by Walter-Feng** [comment]
10e-8 is about the margin of judging whether two numbers are equal - for example in periodic calculation, 10e-8 can be a tolerable error. In FCI we are not calculating integrals, not many operations are involved, so it should be around 10e-12 for the error.

But the case here is slightly different. I am guessing you are assuming  < hf_gs |H| single_excitation > to be always zero, but as far as I recall, there is no guarantee that this is true. I can only recall that <ground state | H | first excitation state> is zero. Make sure these are zero or non-trivial.

**Comment by pkozlows** [comment]
could you take a quick look at the linked code in which I have some questions about the nearby assert statement tolerances? :)
the format for my argument of the Condon function are: ((bra_alpha, bra_beta), (ket_alpha, ket_beta)), where everything is in terms of spatial orbs
https://github.com/pkozlows/fci/blob/6df90b25de688fc79fa0c6f562d31ab898141d5b/slater.py#L123
below linked line <hf_ground_state |H| single_excitation_from_gs> =~1e-8, whale above the link line they are ~1e-16. I don't know if I should be concerned about this detail, or if I should concentrate my debugging efforts elsewhere.

**Comment by Walter-Feng** [comment]
I checked the elements and they do get 10^-8 values, but I am not convinced that these should be equal to 0. I still believe these are actually finite values instead of pure zero, otherwise my eigenvalues cannot be within 10^-12 error.

**Comment by Walter-Feng** [comment]
Maybe it's true that <HF ground state | H | single excitation> is zero, but the SCF convergence in HF ground state can only make it around 10e-8 error. As far as I check, I tend not to think there's critical error behind.
