### ISSUE TITLE
learning Davidson diagonalization

### ISSUE THREAD

**Issue by pkozlows** [pkozlows/fci#25]
How did you learn about the Davidson algorithm for matrix diagonalization? I noticed that there is a section in Helgaker's book on CI optimization, which includes a discussion on the Newton step and the Davidson approximation. However, it is fairly dense upon first glance. Maybe this is natural because if it were trivial, it would not be a part of this project lol

**Comment by Walter-Feng** [comment]
This one was fairly easy, I recall I read Davidson's paper as well as a review of that. Fairly easy.
