### ISSUE TITLE
handy indexing/addressing

### ISSUE THREAD

**Issue by pkozlows** [pkozlows/fci#27]
Do you have any advice on how to think about starting this part of the project? I understand that this might be the hardest part of the project, so it might be tough to do a lot of prior planning. I don't have any unit tests, like for the h Fock energy or brillouin's thm for single excitations from the ground state, one I was implementing the Slater-Condon rules. I'm mainly curious as to how you've started this part. I understand that for implementing the Davidson algorithm, there weren't any unit tests, but there are a lot of resources online, which I was about to read to get a better understanding. Is there anything like that here? I have read their 1984 publication a few times over, and I understand some things that I wouldn't have before, like what alpha and beta strings entail. But other than those elements, it is quite dense.

**Comment by pkozlows** [comment]
I suppose a good way to start would be to figure out how to address the spin strings. And then also to implement a face factor. Are there other elements that you suggest I think about in the beginning.

**Comment by Walter-Feng** [comment]
No, honestly what I felt is the first part, i.e. familiarizing FCI language, was the hardest part. KH algorithm was only a one-week task - which is definitely based on mastering the FCI matrix.

First you might want to sort out the indexing - I was having no problem with this as my sorting of the determinant strings was exactly the same as how it was done in the paper.

Then you would like to unravel the one-particle excitation matrix, including why you need it, and how it bridges to the Full CI. Then it's a one-step process that goes to Full CI energy that combines one-particle excitation matrix and two-electron integrals.

**Comment by pkozlows** [comment]
This is probably an important detail for me to understand at this point, but what is the difference between a scaler and vector machine that they reference in the paper? My understanding is that a vector machine would be used for parallel computing on a cluster, but if I'm just doing it on my personal computer, am I using a scaler machine? is this a detail I should read more about?

**Comment by Walter-Feng** [comment]
Basically that's how I understand as well - there's the SIMD thing that handles add/multiply operation for multiple numbers simultaneously, to achieve maximum FLOPs. But no, you don't need to care about these when writing FCI. Just try to use numpy's own operations as much as possible, instead of writing nested for loops.

**Comment by pkozlows** [comment]
<img width="520" alt="Screenshot 2023-06-22 at 2 22 58 PM" src="https://github.com/pkozlows/fci/assets/59596755/a2efcec2-9092-4c77-8749-7be759a13450">
<img width="513" alt="Screenshot 2023-06-22 at 2 23 30 PM" src="https://github.com/pkozlows/fci/assets/59596755/d82fe680-89be-4cb6-ba83-669f119d623d">
I'm struggling to understand this excerpt from the paper. I am understanding why they give the letter "L" to the orbital number, why they give the letter "M" to the number of orbitals, and why they assign the letter "N" to the number of electrons in the system. However, I don't know why they assign the letter "K" to the electron number because I thought they should be indistinguishable, sober should be no electron number? We can't just say that electron 1 is an orbital 1 electron 2 is an orbital 2 and electron 3 is an orbital 4. All that matters is that all three orbitals are occupied. So, where does the electron label matter? I'm failing to understand this point, so Perhaps I am missing something major?

Then, I am confused as to why they are defining a function (Z) that is supposed to address the whole CI vector, and then they use the same function to help denote the address of an individual spin string, which helps to compose A CI vector.

I understand the concept of spin strings, which helps me grasp a considerable amount of the paper, but clearly, it is not enough to fully understand the indexing part yet. So, your advice is probably what I need to start with:

"First, you might want to sort out the indexing - I had no problem with this as my sorting of the determinant strings was exactly the same as how it was done in the paper."

**Comment by pkozlows** [comment]
and then I understand what the first and third part of this list are supposed to be, but is the 2nd
<img width="512" alt="Screenshot 2023-06-22 at 3 12 11 PM" src="https://github.com/pkozlows/fci/assets/59596755/ebd82a94-d682-4a58-bb5f-15ba0eb2e085">
 part the same as just the computing the face factor between the single replacement and the original string, as we did it in the first part of the project, or is it something different?
