### ISSUE TITLE
Need to think of algorithm to generate all unique cofigs

### ISSUE THREAD

**Issue by pkozlows** [pkozlows/fci#3]
https://github.com/pkozlows/fci/blob/2f623d2c4f7fa6f20b6765b0ccd47719bca4d3a2/%20main.py#L15-L16

 would I coltish this by keeping all but one of the e- stable, and then vary the independent e- across the available spin orbitals one by one? Would it be hopeful to implement a random walk for the purpose of coming up with this algorithm, or is there a different method you would recommend?

 I know that you are nice to me, but in future if I'm doing some cold evolvement that I want another person to look at, well my typos with surrounding context be enough for them to understand my meaning? The alternative for me, is to go back and edit the typos in my dictation after I dictate everything, which may take a little bit more time for me, but it is more worthwhile for someone to be able to understand my meaning.

**Comment by pkozlows** [comment]
How should I systematically generate all unique configurations, utter than the front state determinant adjust generated?

**Comment by pkozlows** [comment]
>> The alternative for me, is to go back and edit the typos in my dictation after I dictate everything, which may take a little bit more time for me, but it is more worthwhile for someone to be able to understand my meaning.

 This draft a dating actually doesn't take up too much time for me, but any motor step which takes time for me that I can laminate is helpful, in makes sense.

**Comment by Walter-Feng** [comment]
Your first step was assigning index to spin orbitals - which is good. Btw this line may be better
```
Spin_orbs = list(range(1, 2 * n_orbs + 1))
```
And it would be even better you get used to the python way of indexing, which is, starting from 0. So it would be
```
Spin_orbs = list(range(2*n_orbs))
```
And even better, you don’t explicitly write `spin_orbs = …` but keep in mind that the indices of spin orbitals are ranging from 0 to 2*n_orbs - 1. But this is some trivial coding suggestions.

In the code you have referred to in this issue, I can see that you are trying to add a ground state determinant. Make sure how you are aligning the spin orbitals, whether it’s all up then down, like
11111… 1 0000…. 0
Or 
10101010…..

Generating all the determinants following this way may be harder than what you think, as the electrons that already took occupation of some spin orbitals will affect how the remaining electrons get their seat. It will most likely be a recursive algorithm, but you can skip the details and directly use the python `itertools` library that automatically generates combinations. 

Forget about random walk. I only mentioned it in case that you are feeling afraid of writing a project in an actual programming language, but you are not. So random walk may not be of any help to you writing full CI.

**Comment by Walter-Feng** [comment]
For now the typo is not harming anything as I know exactly what we are trying to do, but it may cause some trouble reaching a complete understanding in the future (maybe not in this project) especially when you come up with something new or complicated. I understand that typos are hard to fix for you, so no worries at this stage.
