### ISSUE TITLE
Code unrelated questions 

### ISSUE THREAD

**Issue by pkozlows** [pkozlows/fci#4]
>> For now the typo is not harming anything as I know exactly what we are trying to do, but it may cause some trouble reaching a complete understanding in the future (maybe not in this project) especially when you come up with something new or complicated. I understand that typos are hard to fix for you, so no worries at this stage.

I think I see what you mean. If I do more collaborative code development in the future, I would want to minimize the typos. Also, hopefully with time and as my recovery progresses, hopefully there won't be as many dictation typos to deal with in the future. I am also planning on working with my speech therapist on dictating prose and also on using dictation to program, so that should help a little.

Also, I've been wondering whether branching feature in git will be helpful for me in this project? Or is branching more advanced concept that I would use in the future when working on collaborative code development?

I know you unit testing is a good tool to use for code development, but I don't know if I'm at that point yet in my project where I needed yet. If you could let me know at what point I would want to start using it, that would be much appreciated.

As always, thank you for being incredibly helpful and patient and hopefully I will start to make more progress on my project now, now that I'm using more dictation.

**Comment by Walter-Feng** [comment]
Branching will be super useful, even when it is only you that are contributing to the repository. The main point of branching off the main, I believe, is to avoid contamination among different blocks of code. This way you can make sure one specific version is actually working, and a git diff between branches helps identify which sections of the code are actually needed.

But maybe not in this project, as it will be a small project and everything can be under your control. It also adds unnecessary difficulty as it requires some merging procedures that, I would guess, may not be easy for you.

Unit tests are also important, 1st is *we* - both the developers and users - can make sure the code is actually working, and 2nd, users can learn via unit tests how your code can be used. 

I don't think there's a gold standard for the timing of writing unit tests, but generally, whenever you build a function that involves multiple steps and is not super clear to see the result, you will eventually need a unit test and verify the result is indeed what you need. This helps you rule out potential bugs and reduce your effort in debugging in the long run.

I would say, if you manage to write an algorithm for generating the determinants, you can write a unit test for that generator and manually inspect if you have really generated everything, and they are in good data structure.

**Comment by Walter-Feng** [comment]
Regarding this, you will also benefit from parsing the whole project into different functions. Only functions can be properly tested in unit tests, plus you can localize the problems you need to solve. So more like

determinant generator -> ? -> ... ? -> FCI hamiltonian generator -> ? -> .... ? 

and each step can be wrapped as a function. The question marks represent some steps in this project that you will need to figure out.

**Comment by pkozlows** [comment]
Do you have any preference for what module to use for unit testing?  I am relatively new to code defacement, so I have never done unit test per for.I notice that there are multiple molecules, such as unittest or doctest.

**Comment by Walter-Feng** [comment]
For now you can just use `assert` keyword, for example
```
assert(1 == 0)  # throws an error
```

This works as simple unit tests.
