### ISSUE TITLE
how to generate all unique pair of dets for comparison

### ISSUE THREAD

**Issue by pkozlows** [pkozlows/fci#5]
Would I use something witten itertools module to generate all unique pairs of my iterator that contains the determinants or would I want to learn something new? This is the iterator object a taking about. https://github.com/pkozlows/fci/blob/c1ce6377f9f689e6267298090f543100a72dfd31/%20main.py#L9

**Comment by Walter-Feng** [comment]
I don’t think you need to make it as an `iter` object - I would suggest you might want to turn it to something like `list`, which you actually did before this line. `list` is iterable in python, i.e. you can do `for i in some_list`, so no need for extra step that converts it into iterator.

Now you can think about how to make pairs, although I don’t guarantee you that what you have written  is correct.
