### ISSUE TITLE
Implementation of second quantization

### ISSUE THREAD

**Issue by pkozlows** [pkozlows/fci#7]
Can you take a look at recent commit for squant.py and tell me if it's the right start tp be making for implementing Second Quantization?

**Comment by pkozlows** [comment]
Nevermind, I think I know that this implementation is probably right. I will ask you more questions when I am actually unsure about what I am implementing. No need to take a look at my code if you haven't already.

**Comment by Walter-Feng** [comment]
Yup, and it is also an important skill to debug and find the problem yourself. I also have many situations where a bug stuck me for several days, or even weeks. 

Be calm, be patient, and trust yourself. Good coding habit also helps you debug.

**Comment by pkozlows** [comment]
Can you give me any ideas for implementing the second quantization commutation relations? I saw that the numpy module has a .kron() method, but this is used for arrays. I have second quantization operators of the form (<orb#>, <0 or 1>), so the built-in numpy Kronecker delta method would not be useful here.

**Comment by pkozlows** [comment]
Sorry, I wasn't descriptive. Beast on my code from braket.py, once I have converted my determinants to a second quantization form, I will have a list that looks like [(1,0)...(7,0),(2,1)...(7,1)], were the form of these second quantization operators to which I deconstruct my determinants are given in the above comment. For implementing second quantization, I would want to do something bringing (7,0) and (7,1) together and then cancelling using anti-commutation relation. How would I implement this? If what I'm saying doesn't make enough sense, just let me know and I will put something together that explains my question Brother on latex tomorrow.

**Comment by Walter-Feng** [comment]
Now your explanation looks super clear. 

By the way, computers do not necessarily need to know the symbolic expression of maths, for example, the Kronecker delta. When programming, it will be easier to do something like
```
if a == b , then ....
```
So in this case, moving operators around can be better represented as changing the order of numbers in a list. When changing the order of two neighboring numbers, if they are not a pair, you can simply exchange their order, but assigning a negative sign. So yes, it's a sort, but you also need to count the number of operations to get the sorted order.

I'll stop here for now - hopefully I have given just the right amount of tip that helps you push through, but not decreasing the difficulty.
