### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by pkozlows** [pkozlows/fci#8]
I now recognize that it is important for functions to be bulletproof, while I'm testing a new function with them. I believe this means that I really want to learn how to test comprehensively. I don't want you to look at the details of it, but if you could look at the structure of `braket.py` and tell me how you would test such an object. 

Also, how general do I need to be when testing my units? I can see that the `random` module with the `randint()` function could be useful in my case, but how big of a system do I need my functions to be working for? For example, for the number of electrons in the system, is `randint(1, 6)` sufficient? So far, I have been testing my functions and units against a  specific determinant pair in the six electron and six orbital system, which I understand is definitely not enough. 

I asked this already, but would it be better to just test with `assert` keywords or to use the built-in Python `unittest` module? I figure that I will be doing a lot of testing from now on, so if it would be worthwhile, I could definitely invest some time to learn the `unittest` module.

**Comment by pkozlows** [comment]
I imagine that branching will be similar to testing, in that I will realize at what point in the project I will need it.

**Comment by Walter-Feng** [comment]
Well I have not read your code thoroughly, but the lines of `print` you have written below can already be a unit test. just converting `print` to some `assert` will just function as a simple unit test. If you don't feel like this is proper unit test, then sure you can explore the unit test modules, which you may benefit from in the long run.

Being bulletproof is hard to achieve - I recall the joke of "I have made unit tests of customer's asking 1 pint of beer, 1.34 pint of beer, -2 pint of beer. My program crashed when customer asked 'where is the toilet'". Not super relevant to our topic, but you may encounter some situations where, the functions that have passed the unit tests still have bugs that are not covered, and you need to debug later.

having random number of electrons and orbitals is good, but not necessarily you will also need to do a large system like 100 electrons and orbitals. If your code is generic enough, e.g. did not exactly classify the number of electrons, usually a test system with size similar to your goal will be good. Maybe you want to test some super small case, e.g. 1 electron and 2 orbitals, just in case. They will be easier to identify the bug, if any.

**Comment by pkozlows** [comment]
>Being bulletproof is hard to achieve - I recall the joke of "I have made unit tests of customer's asking 1 pint of beer, 1.34 pint of beer, -2 pint of beer. My program crashed when customer asked 'where is the toilet'". Not super relevant to our topic, but you may encounter some situations where, the functions that have passed the unit tests still have bugs that are not covered, and you need to debug later.

LOL
