### ISSUE TITLE
Accessing the given integrals

### ISSUE THREAD

**Issue by pkozlows** [pkozlows/fci#9]
my question  has been pushed to the dir of questions.

**Comment by pkozlows** [comment]
Actually, I am working on pushing this, so give me like fifteen minutes before I get this up and you look at it.

**Comment by Walter-Feng** [comment]
h1e is symmetric. You may see some 10^-16 error but that's normal for double precision.

h2e is aligned as [  i j | k l ] , and indexed in numpy as `h2e[i, j, k, l]`. So it has 8 fold symmetry, i<->j, k<->l, (ij) <-> (kl).

I recall there are different notations, it should be [ ij | kl ] = < i k | j l >

**Comment by pkozlows** [comment]
I pushed a new item to the questions directory, if you could take a look at it

**Comment by pkozlows** [comment]
I realize that the problem of which into integral indices to assign to certain determined pairs might be worth for me to think about more, so give me some more time.

**Comment by pkozlows** [comment]
I guess what it boils down to is whether I should be presenting the summation over N particles by the np.sum() function. I initially thought that this would be the best way to do the to the integrals, but now I am not so sure. There might be a better way to think about this problem in second quantization, but I am only familiar with using second quantization when there is a difference between determinant pairs, such that there are creation and annihilation operators involved. I am not comfortable with working in second quantization when there is no difference between determinant pairs, as is the case here. As always, let me know if I am not making much sense, in which case I will write up a LaTeX file.

**Comment by pkozlows** [comment]
Maybe this is precisely what I need to figure out myself, but I am confused about how to represent this quantity in my Python code.

 https://github.com/pkozlows/fci/blob/807e7ae1f21362aa665d21c7a850d275cde22346/questions/2-1_v2.pdf

**Comment by pkozlows** [comment]
Apologies for the spam, but I was thinking about this problem when I was lying in bed at night and I realized that summation over a given indice could be well represented by a for loop.

**Comment by Walter-Feng** [comment]
For loop is good, but is super slow. You can take a look at numpy.einsum.
